import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

print("Authenticating Access To Database...")
cred = credentials.Certificate("serviceAccountKey.json")    #"serviceAccountKey.json" contains the unique secure key generated by firebase to make changes to the database
firebase_admin.initialize_app(cred, {
    'databaseURL': "https://automated-attendance-sys-187b7-default-rtdb.firebaseio.com/"    #Linking to database on firebase (key: value pair, json format)
})
print("Access Granted!")

ref = db.reference('Students')  #Creating a folder 'Students' inside the database to which each of the student's data will be stored in a sub-folder named using their student ID

print("Uploading Data To Database...")
data = {
    "852741":
        {
            "name": "Emily Blunt",  #7 key: value pairs within a key: value
            "major": "Economics",
            "starting_year": 2020,
            "total_attendance": 10,
            "standing": "G",
            "year": 2,
            "last_attendance_time": "2022-12-20 00:23:34"
        },

    "963852":
        {
            "name": "Elon Musk",    #7 key: value pairs within a key: value
            "major": "Aerospace Engineering",
            "starting_year": 2022,
            "total_attendance": 2,
            "standing": "B",
            "year": 1,
            "last_attendance_time": "2022-12-24 00:12:23"
        },

    "20220050":
        {
            "name": "Joel John Varghese", #7 key: value pairs within a key: value
            "major": "CSE",
            "starting_year": 2020,
            "total_attendance": 50,
            "standing": "G",
            "year": 3,
            "last_attendance_time": "2023-03-21 18:46:23"
        },

    "20220026":
        {
            "name": "A S Swan",
            "major": "CSE",
            "starting_year": 2020,
            "total_attendance": 1,
            "standing": "G",
            "year": 3,
            "last_attendance_time": "2023-01-01 00:00:00"

        },

    "20220041":
            {
                "name": "Govind MJ",
                "major": "CSE",
                "starting_year": 2020,
                "total_attendance": 1,
                "standing": "G",
                "year": 3,
                "last_attendance_time": "2023-01-01 00:00:00"

            },

    "20220054":
            {
                "name": "Lakshmi Manoj",
                "major": "CSE",
                "starting_year": 2020,
                "total_attendance": 1,
                "standing": "G",
                "year": 3,
                "last_attendance_time": "2023-01-01 00:00:00"

            }
}
print("Data Uploaded To Database!")

for key, value in data.items(): #Storing each key, value pair in local "data" variable to the database
    ref.child(key).set(value)